### ISSUE TITLE
Vertex morph weirdness

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#18] opened 2016-07-20 18:04 UTC
Check out http://www.mediafire.com/download/jadx135w5pbn866/vertexmorphweirdness.zip .  It contains three files: 4hoodies.pmx is the file I imported into Blender, untitled45.blend is the most recent Blender save, and untitled44.pmx is the exported file.

For several of my materials, I removed all shape keys so that I could use modifiers (I think just 'mirror' during this session).  After applying modifiers, I recreate a basis shape key, mostly out of habit-- I've had trouble when failing to recreate a basis for each material and relying on joining materials to recreate the basis shape key.

Check out the vertex morphs.  The first morph in the list is the blink.  You'll notice that, even though the tank top somehow got all screwed up by this morph (probably Blender's fault, not mmd_tools' fault, although I'm not sure), the morph is still working on the face in Blender.  However, on the exported file, the blink no longer works.

These morphs seem to have been reattached from their original materials.  Deleting the vertices of a few of the hoodies in PMXE kills off all the facials.

In an attempt to work around this, I tried exporting with different materials as parent objects, or exporting as separated objects, but this happened no matter what I did.

**Comment by powroupi** [comment] 2016-07-21 03:05
Try it: :smile: 
- 1. open **untitled45.blend**
- 2. RMB select the **'main'** object (which is called **'016_face'**)
- 3. Tab enter edit mode, _(optional) hit **'a'** twice to deselect all (just make sure nothing selected)_
- 4. go to material panel, LMB click the material **'tank'** and hit 'Select' button _(the middle button of Assign/Select/Deselect)_
- 5. go to 3d view, hit **'p'**, seperate selection
- 6. Tab back to object mode
- 7. RMB select the **'tank'** object (which is called **'016_face.001'**)
- 8. go to mesh data panel, remove all shapekeys of the **'tank'** object, and recreate the **'Basis'** and **'TankHike'**
- 9. in object mode, RMB select the **'tank'** object then Shift+RMB select the **'main'** object, then hit 'Ctrl+j' to join back _(it's better to select the **'main'** object always at last)_

ps.
- At step 8, there are several ways to do, for example: delete the **'tank'** object and import a new one...
- Any modification of the mesh in blender may make the uv morphs unusable, so be attentive!
- It seems that some of the related mesh of material morphs are out of sync, you may need to reconfigure it manually if you want to check the values of material morphs in blender. But fortunately it does not affect the exporter.

**Comment by nathanvasil** [comment] 2016-07-21 05:14
I'm not sure if that was intended to address the disappearing morphs issue, which is still present after following your instructions.  (It does address the exploding morphs, which I believe is just from Blender going crazy after I delete a few vertices, not anything having to do with mmd_tools.)

**Comment by powroupi** [comment] 2016-07-21 06:42
Okay, i noticed that and found the root cause. it should be solved now. :smile: 

If you don't want to download [dev_test](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip) again, just go to mesh data panel and unlock/unpin the **'show_only_shape_key'** (which is in the `Shape Keys` panel of mesh data panel, the **pin** icon) to all meshes in your MMD model. (go to 'mmd_utils' panel, you should see 3 objects in `Meshes Sorter` panel). That's why the vertex morphs don't export properly.

In order to export more accurately, you can mute the **'Armature'** modifier of all meshes in your MMD model, so the vertice position will not be affected by the armature. Also change the armature pose state from **'Pose Position'** to **'Rest Position'** in the `Skeleton` panel of armature data panel, so the bones can be exported more accurately. :smile:

**Comment by nathanvasil** [comment] 2016-07-21 15:56
Oh, thanks-- I didn't even realize I had "Always show the current shape for this object" pinned (I believe that's what you're talking about?)  I already knew that would cause problems, but it's easy to forget to unpin it after doing morph editing.  (There's some other weird behavior associated with that button, probably not worth getting into because they're so minor and easily worked around.)

I'm more interested in what you're saying regarding the armature.  I've noticed vertex and bone corruption that seems small, gradual, and steady (I guess I'd prefer it was just catastrophic and obvious), and that makes it almost impossible to maintain symmetry.  I've been in the habit of just deleting the armature modifier, but since that's been replaced with mmd_bone_order_overrride, I've been leaving it.

Will deleting mmd_bone_order_override relax the armature on the mesh from which it's deleted?  With this modifier deleted, is it still necessary to set the armature to rest position?  I'm afraid I'm not familiar with Blender animation, I've just been using it for meshes and such, and MMD for the animation.

Do you think it might make sense to have this load to "rest" by default?  If you're using Blender to animate, it will be impossible to forget to change this, because otherwise, it will be impossible to animate; but if you're not using Blender for animation, it's a very easy thing to miss or forget.

Finally, might it make sense to create an abstract "main object" for a Blender import?  It's not always very obvious which the main object is, especially after a few separations, joins, and deletions, and there might be cases where one wants to get rid of armature-driven corruption on every material while maintaining bone order.  There already is a parent object for everything-- would it only be necessary to create some kind of invisible, delete-on-export mesh to allow this parent to hold the bone order override?  Ideally, an export script could just check for the presence of any main parents and, if a particular hierarchy didn't yet have an appropriate main-object parent, use the first main object in the scene to drive the export.  This could also simplify a lot of problems that come up when trying to get new meshes (from primitives or curves) into PMXs, something that still causes intermittent problems for me.

Sorry, this is probably long and hard to understand!  Happy to explain anything, happy to hear your thoughts.  I'm very happy with the state of your mmd_tools currently and I'm just in the habit of posting an issue anytime I run into a problem-- I figure you can decide whether an issue is worth dealing with and it's better to know about any particular issue, even if that issue is small.

**Comment by powroupi** [comment] 2016-07-22 01:38
> what you're saying regarding the armature.

Well, it is a suggestion that you can do before exporting a MMD model in blender. I don't think that make sense for users to do that, so I'm finding a way to make it automatic on exporting, and then you can ignore it. (That's just for exporting, so do not be confused with model editing in blender) :)

> I've noticed vertex and bone corruption that seems small, gradual, and steady

Sadly, the custom normals may not work well after modifying the mesh. You may uncheck **''Auto Smooth** of mesh object in mesh data panel. And **remove doubles** to get smoother faces, but doing so may corrupt the shape keys, it's hard to handle it. >_< 
And the `'bone id'` of this addon does not work well when you duplicate bones, so ALWAYS create new bone by using `Shift+'a'` or `'e'` to extrude from active bone when editing armature.

About `'mmd_bone_order_overrride'`, it is just a name of modifier that tell the exporter to use the vertex group order of that mesh object as the MMD bone order. You can remove it anytime, and put it back to the mesh which you defined the "bone"(vertex group) order when exporting.

About `'Rest Position'`, as i said above, it is not necessary but a suggestion. Mute `'Armature'` modifier for exporting more accurate mesh, and set `'Rest Position'` for more accurate armature. Because sometimes the constraints may slightly change the armature, and cause the vertice position offset. That's why i suggest to mute `'Armature'` modifier (oh...actually mute `'Armature'` modifier should be enough, sorry <3) when exporting.

About `"main object"`, it is for easier explaination. Since we are fixing the 'tank' issue on 'main' object (which is called '016_face'), it should make sense that we join the seperated/fixed 'tank' object back to the 'main' object, right ?! ...So do not be confused. :smile:

**Comment by nathanvasil** [comment] 2016-07-22 03:10
Hmm.

There no longer is an "armature" modifier on my imports.  There's only the mmd_bone_order_override modifier.  That's with the second to last devtest build.

Setting to rest pose isn't preventing the vertex corruption.  I don't think it's a custom normals issue either.  I'll try and get a good example and create a new issue.

I understand now regarding the main object and mmd_order_override.  It's not a modifier with any special information contained in its parameters, and I can just add it back to any mesh, correct?

**Comment by powroupi** [comment] 2016-07-22 05:11
> There no longer is an "armature" modifier on my imports.

`'Armature'` is the modifier's type, `'mmd_bone_order_overrride'` is the modifier's name, you can rename modifier's name whatever you want. Currently, the importer just rename the 'Armature' modifier's name to `'mmd_bone_order_overrride'`. In blender, we can add an 'Armature' modifier from modifiers panel (Add modifier -> Deform -> Armature). The default name of 'Armature' modifier is "Armature". Ha Ha ...so confusing! :sweat_smile:

> Setting to rest pose isn't preventing the vertex corruption. I don't think it's a custom normals issue either. I'll try and get a good example and create a new issue.

I'm curious! Waiting for the issue. :smile: 

> I understand now regarding the main object and mmd_order_override. It's not a modifier with any special information contained in its parameters, and I can just add it back to any mesh, correct?

Yes, add it back to any mesh that you want to control the MMD bone order via vertex groups order when exporting the model. So there just need only one. :)

**Comment by nathanvasil** [comment] 2016-07-25 22:21
Thanks for the explanation.

I believe that the vertex corruption was from the armature after all.  Leaving it on leads to slight distortions in the mesh that add up over a number of import/export cycles.  It's an easy thing to miss, unfortunately.

**Comment by lordscales91** [comment] 2016-08-01 11:50
@nathanvasil Is this fixed on the latest version? Confirm it as soon as possible so then @powroupi can close this. Do the same for your other issues.

**Comment by nathanvasil** [comment] 2016-08-01 21:46
I haven't tested how the latest devtools affects vertex morphs.  I won't be able to test this any time soon; I'm currently working on some non-modelling stuff.  If you're confident that the issue is solved (and truth be told, it's a minor issue, one that I shouldn't have even reported), then go ahead and close the issue.

Re: https://github.com/powroupi/blender_mmd_tools/issues/12 , all issues in that thread are resolved to my satisfaction, and the only reason I haven't closed that issue already is because you were discussing testing your base_texture_folder addon property in that thread but hadn't yet.  Any time that you've tested that, it's appropriate to close the issue.

My third open issue, https://github.com/powroupi/blender_mmd_tools/issues/13 , hasn't been dealt with.

**Comment by lordscales91** [comment] 2016-08-02 10:00
About #12 I have already tested it and improved the feature with my last PR #19 so you can close it yet. (Only the person who opened the issue and the repo owner (powroupi) can close it)

**Comment by powroupi** [comment] 2016-08-03 13:08
> And the 'bone id' of this addon does not work well when you duplicate bones, so ALWAYS create new bone by using Shift+'a' or 'e' to extrude from active bone when editing armature.

Sorry here, i have to correct myself: It is ok to duplicate bones **only if the bone id is -1**. You could see `ID: -1` in panel `MMD Bone Tools`, just under the label `Name(Eng):`.

And it is fine to keep issues open, i don't mind. :smile:
I know my fixes might not be user friendly enough, there still have room to improve it. So you can keep issues open until someone or me to improve it. (but i'm sure `'show_only_shape_key'` issue is fixed) :sunglasses:

**Closed as completed** 2016-08-03 14:24 UTC
