### ISSUE TITLE
Blender 2.91 after installation error

### ISSUE THREAD

**Issue by Ddotchannel** [powroupi/blender_mmd_tools#324] opened 2021-01-18 13:00 UTC
Everytime I check mark it after it installed, it gives me this error.
![image](https://user-images.githubusercontent.com/77622693/104918577-0d88a900-5939-11eb-8d38-6db4b0c8e57b.png)

**Comment by Hashi-13** [comment] 2021-01-28 09:04
man, it’s the same for me, nobody managed to solve it? Perhaps version 2.75 will do the trick.

**Comment by SkyNinja** [comment] 2021-02-11 02:09
Well, this sucks. AMD broke the hell out of Blender and blamed the Blender devs for it. The devs have managed to work around AMD's fuckery, but every single version of Blender prior to 2.91 is now broken on AMD cards, making this unusable.

Man, fuck AMD.

**Comment by cabiste-dev** [comment] 2021-02-14 02:59
> man, it’s the same for me, nobody managed to solve it? Perhaps version 2.75 will do the trick.

and when will this version come ?

**Comment by Hogarth-MMD** [comment] 2021-04-14 04:21
You could try an earlier version of Blender while you wait for the bug to be fixed.
I don't understand the references to Steam and steamapps. Maybe you need to explain what you are doing and how that works.

**Comment by powroupi** [comment] 2021-05-21 01:44
Duplicate of #292

**Closed as completed by powroupi** 2021-05-21 01:44 UTC
Labels: Installation
