### ISSUE TITLE
.smd won't export as .pmx

### ISSUE THREAD

**Issue by kerplunk86** [powroupi/blender_mmd_tools#96] opened 2018-01-05 21:26 UTC
It will only export as .fbx which screws up the bones just trying to convert Gmod people to mmd ppl there's nothing in the console window whenever I export to pmx

**Comment by Hogarth-MMD** [comment] 2018-01-05 22:24
Converting and exporting characters to pmx has not yet been implemented in mmd_tools, but hopefully this will be fixed soon. See:
https://github.com/powroupi/blender_mmd_tools/issues/80

**Comment by nathanvasil** [comment] 2018-01-05 22:52
Maybe I misunderstand, but exporting .blends to .pmx is implemented.  I'm not familiar with .smd file format, but I expect kerplunk just needs to make a new MMD model and replace the armature that's parented to the MMD model empty, as discussed #80 that you link.

@kerplunk86 keyplunk86, if you want to link to a .blend file (containing your imported .smd), I might be able to tell you with more certainty what the problem is.

**Comment by Hogarth-MMD** [comment] 2018-01-06 00:22
It is possible to export a model to .pmx using the workaround suggested by @nathanvasil , but the exported model will have various errors. Bones which should be rotate bones are exported as rotate-move bones. Materials exported incorrectly. Bones and morphs not added into display panel groups. The model is too small and needs to be resized. Shape keys with no English names.

**Comment by powroupi** [comment] 2019-09-24 13:45
See similar issue powroupi#193.

**Closed as completed by powroupi** 2019-09-24 13:45 UTC
