### ISSUE TITLE
add bone pose morph (after ph)

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#122] opened 2018-03-15 00:00 UTC
Hello @powroupi!  I just added a bone pose morph to a model using mmd_tools. This is a very nice, excellent feature of mmd_tools. Thank you for programming this very nice, excellent feature. It worked beautifully, but with one small problem. If a bone pose morph moves a bone which is controlled by physics, the bone pose morph does not work in MMD unless the After Ph (solve bone after physics). option is enabled for the bone (which can be enabled in PMX editor after export from Blender). (MMM does not have this issue, though.)

**Comment by powroupi** [comment] 2018-03-15 09:05
Do you want to enable a bone's After Physics property automatically on export if the bone has any bone morph? Would it cause any other issues if I add this feature? Is there any good idea? :thinking:

**Comment by Hogarth-MMD** [comment] 2018-03-15 13:31
What about automatically adding After Physics when a bone morph is created? This is only needed for hair, skirt and breast bones. I don't know if After Physics would create any issue for other bones. This is a good question. :worried:

**Comment by nathanvasil** [comment] 2018-03-15 18:16
It could create issues to do it automatically on any bone morphs created.  Messes with the order of evaluating bones, could break the hierarchy if you do it on every bone morph created.

You could trace the bone heirarchy stack, and if its a bone dependent on physics apply it then and only then.  If you wanted.  But making bones evaluated after physics works a little strangely-- you don't get the exact position of the physics.  You get something that's like half-physics.  I'm not sure that the feature is working as intended even in MMD.  If you were to import a model, change one of its bones to after-phys, then export it, you'd end up with altered deformation even without using the bone morph.

There is a box for "After Dynamics"  in bone's MMD Bone Tools subsection of the bone tab, which I believe exports the bone as an after-physics bone.  I would think that's sufficient.

**Comment by powroupi** [comment] 2018-05-26 00:45
Agree with @nathanvasil , users could change that property using PMDE/PMXE or `mmd_tools` if they want. I'd like to close this issue. :)

**Closed as completed by powroupi** 2018-05-26 00:45 UTC
