### ISSUE TITLE
mmd I'm getting this error in blender 2.90.0

### ISSUE THREAD

**Issue by nedomenya** [powroupi/blender_mmd_tools#308] opened 2020-09-22 16:38 UTC
![SAVE_20200922_223810](https://user-images.githubusercontent.com/59362649/93911544-58483a80-fd24-11ea-8946-f0287d299501.jpg)
Please, help me!

**Comment by DevriesL** [comment] 2020-10-06 15:17
1, Remove mmd_tools and install again
2, Go to [File]->[Defaults]->[Load Factory Settings], and then enable mmd_tools again

**Comment by kezh-kia** [comment] 2020-10-13 14:31
> 1, Remove mmd_tools and install again
> 2, Go to [File]->[Defaults]->[Load Factory Settings], and then enable mmd_tools again

I have the same issue in Blender 2.83 and this does not work apparently :/

**Comment by powroupi** [comment] 2021-05-21 01:44
Duplicate of #292

**Closed as completed by powroupi** 2021-05-21 01:44 UTC
Labels: Installation
