### ISSUE TITLE
Using lightmap and multiple UV sets for GI

### ISSUE THREAD

**Issue by ray-cast** [powroupi/blender_mmd_tools#68] opened 2017-07-22 16:50 UTC
i have been trying to make an GI for MMD, but that must be compute some data from the second UV sets, because most of the model are work in the first UV sets with mirrored UV coordinates.

so is there any way you could make one that can be export multiple/second UV sets to the PMX model? so could you please fill in the blanks for me or others people, that would be great, thank you.

**Comment by powroupi** [comment] 2017-07-23 02:50
Thank you for reporting this issue. :smile: 

It would be easier to do if additional UVs is all at (0, 0) or the same with base UV. But I'm not sure if that will help? Exporting multiple different UV map is a little complex because of the PMX data structure, we need to rip a vertex which has multiple uv points. Currently it is difficult for me to do, sorry. :cry:  I'll keep trying that, or maybe other developers can do that. Thank you. :smile:

**Comment by ray-cast** [comment] 2017-07-23 04:07
Thanks for you reply.

I know that PMXEditor can be copied first UV sets into the second or others UV sets, but if i using LightMapPack to generate new UV coordinates and export them to base UV, that number of vertices will be  greater than the original number and PMXEditor will not work well, so it's hard for me or other people to generate model for GI.

I know adding all the new features takes time and i'm sure that are hard to coding, okay thanks anyway.

**Comment by nathanvasil** [comment] 2017-07-23 04:47
To my knowledge, the reason addUV is difficult is because MMD's addUV is 4 channel when Blender's UV+ is 2 channel.  I see how that complicates things if you want to do it perfectly.

However, I think the main use case for this is exporting lightmap data; there's little reason for addUV outside of lightmaps (except as a hidden pocket to store extra data for a model for various shaders; without a good way to enter this info, it goes unused).  Ray-cast isn't the first person I've heard of having trouble exporting lightmap coords.

Maybe it would be worth doing even if it couldn't be done perfectly?  Discarding third and fourth channels isn't ideal, but it would be better than discarding all addUV.

Finally, a word to @ray-cast : if you're feeling ambitious, check out the Collapse effect, which comes with a script intended to be run in PMXE.  This script creates addUV data.  By studying it, you could create a script to copy UV (exported with lightmap coords) to addUV in PMXE.  That's half the battle; I don't know if there are any copy UV plugins for PMXE to get main (texture) UV back into your main UV, and unfortunately, you couldn't copy in Blender, since addUV gets discarded.

**Comment by nathanvasil** [comment] 2017-07-23 04:58
@ray-cast There's a better, simpler way I just thought of and confirmed, which is to use PMXE export to csv functionality.  By creating a simple plane with UV and add UV coordinates and exporting its vertices to .csv, you can see which columns these belong to; using a spreadsheet program, you should be able to copy these columns.  If you have two models, one with texture UV and one with lightmap UV, you should be able to copy these values over.

**Comment by ray-cast** [comment] 2017-07-23 06:06
yeah, i know and i got a plugin from another developer, it's useful for me and some one (there users know how to rebuild a unwrapped All vertices for lightmap coords and my shader), but for others who used my shader, this plugin is very very hard to use and i think nobody will like it.

Finally, thanks yall for your reply, i'll try to find a better way, instead of blender, i hope that will be useful for other users.

**Comment by powroupi** [comment] 2017-07-24 01:05
Oh, wait, I've figured out a way to export addUV, and I'll make an update soon for you to test it. :smile: 

I use the way that @nathanvasil mentioned before to handle addUV, a addUV will be separated to 2 UV maps, one for xy, one for zw, and will be combined back on export. Maximum 8 UV maps is the only limitation, some UV maps for zw channels will be lost in some cases, but I agree that it is better than nothing. :smile:

**Comment by ray-cast** [comment] 2017-07-24 01:46
I really appreciate your work and help me, it's so great for me.😄
I just need one of addUV with xy channels for lightmap coords, 

but at the same time.
Is there a way you could export addUV with the bent normals or tangents? they can be used for directional occlusion and anisotropic hair, but now it's not important for me.

**Comment by powroupi** [comment] 2017-07-24 02:22
>Is there a way you could export addUV with the bent normals or tangents?

(Do you mean per vertex [normal/tangent](https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas) ?) I think it is possible, and it might be an export option. ...but vertex normal should be already available from a vertex shader, and I don't know how to get tangent/binormal in blender. :cry:

**Comment by ray-cast** [comment] 2017-07-24 03:16
Yea, Tangents can be calculated directly by partial derivative (ddx/ddy), But it's not a smooth tangents with high precision partial derivative.

Because the Shader Model 3.0 cannot support ddx_fine/ddy_fine, this function is supported in the Shader Model 5.0. so i need per vertex tangents for smooth tangents and used for anisotropic hair, and bent normals for directional occlusion.

but they can also be fetched by bent normals map and tangent map, so ignore them.

Finally, thanks for your work.

**Comment by powroupi** [comment] 2017-07-24 05:24
Okay, `mmd_tools` now can import/export addUV. :smile: Currently, `[UV NAME]` store xy/uv channel, `_[UV NAME]` store zw channel, and zw channel will be skipped on import if all values are zero in PMX file. :)

**Comment by ray-cast** [comment] 2017-07-24 05:37
ok, i will DL and play it now, thanks so so much!!!

**Comment by ray-cast** [comment] 2017-07-24 06:10
thanks so much , i got it now
![image](https://user-images.githubusercontent.com/6936875/28510093-de0b86c2-7078-11e7-9722-c6101a559ae8.png)
![image](https://user-images.githubusercontent.com/6936875/28510232-b765a1aa-7079-11e7-935d-15ffb0fe6394.png)

**Comment by Hogarth-MMD** [comment] 2017-07-24 15:28
"Okay, mmd_tools now can import/export addUV.  :smile: "

Yay! :smile: I want to receive a notification every time that a new commit is made to mmd_tools. But there does not seem to be any setting in my Github notifications which allows that to happen. Is this impossible? I am only notified when a new comment is posted in issues.

**Comment by powroupi** [comment] 2017-08-19 01:25
Since this issue has been solved, I'd like to close it. :smile: ( @Hogarth-MMD I'm sorry I don't know how to do that. :cry: )

**Closed as completed by powroupi** 2017-08-19 01:25 UTC
