### ISSUE TITLE
Model Appears Black in Material Preview Mode

### ISSUE THREAD

**Issue by crazy4anime09** [powroupi/blender_mmd_tools#353] opened 2021-06-26 19:42 UTC
In Blender 2.93 some models appear all black or only parts of them appear black in material preview mode, but when I go to render preview mode the materials show up normal. It did not do this in Blender 2.92. Do you know why it is doing this or how to fix it? I am using the most recent version of the mmd tools addon.

![MMD Model Shows Up Black](https://user-images.githubusercontent.com/86533981/123523841-79afcb80-d694-11eb-8d26-1497b9746a9d.png) 
![MMD Model Shows up Normal In Render](https://user-images.githubusercontent.com/86533981/123523849-92b87c80-d694-11eb-834e-352849d7139f.png)

**Comment by powroupi** [comment] 2021-06-27 02:39
I don't have this issue on my system, so I'm afraid I can't solve this issue. :cry: 

I think it might be an issue of your system or your Blender settings. You might try `[File]->[Defaults]->[Load Factory Settings]` to see if the issue still happens. If it still happens, then it could be the issue of your system because it seems that `Material Preview Mode` uses EEVEE render engine, it might happens if your graphic card can't handle it. (not sure :worried: )

**Comment by crazy4anime09** [comment] 2021-06-27 20:01
I tried loading the factory settings, but the issue still happens. You're probably right that it's an issue with my system because my computer is 8 years old, and when I install new versions of Blender I get a message that says limited support. I guess if I want to be able to use newer versions of Blender in the future I'll have to get a new computer lol. 

I tried looking around in Blender to see if I could figure out how to fix it and I did discover a weird fix for it. If I click on a material and go to the shader editor and go to the MMDShaderDev node if I choose any number for the Reflect option the material shows up in material preview mode normally again. The Reflect option is set to 0 for almost all materials normally and in Blender 2.92 it is set to 0 for the materials too. I'm not sure what the Reflect option is used for, but if I want to use MMD models in Blender 2.93 and the materials show up black I'll just have to go to the shader editor to fix them each time. I'll probably stick to using Blender 2.92 for now ^_^

**Comment by nagadomi** [comment] 2021-06-27 20:46
This may be related to the following issues.
[T88754 Intel HD graphics: Changing Roughness Value to 0 causes mesh to be black](https://developer.blender.org/T88754)
mmd_tools changes `Material > Viewport Display > Roughness` to match the MMD material settings(Reflect). The issue may occur when Roughness is not 1.

**Comment by powroupi** [comment] 2021-06-28 03:48
@crazy4anime09, basically assigning 0 to `Reflect` of mmd shader is invalid, I've added a fix for this issue. You might update your `mmd_tools` and try again. You can close this issue If the issue is not happened again. Thank you. :smile:

**Comment by crazy4anime09** [comment] 2021-06-28 04:43
It worked! Thank you so much! I will close this issue now. Thank you so much again! ^_^

**Closed as completed** 2021-06-28 04:43 UTC
