### ISSUE TITLE
Multiple Code Bugs for Mac

### ISSUE THREAD

**Issue by mrrfyW** [powroupi/blender_mmd_tools#306] opened 2020-09-12 19:56 UTC
<img width="802" alt="Screen Shot 2020-09-12 at 3 56 06 PM" src="https://user-images.githubusercontent.com/69284371/93003908-818ced80-f510-11ea-9148-5587a2f6c1d0.png">

Can you please fix these?

**Comment by mrrfyW** [comment] 2020-09-12 19:56
[DELETED FOR PRIVACY REASONS]

**Comment by powroupi** [comment] 2021-05-21 01:43
Duplicate of #292

**Closed as completed by powroupi** 2021-05-21 01:43 UTC
Labels: Installation
