### ISSUE TITLE
Textures being exported in a fashion leading to PMXE errors

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#29] opened 2016-09-30 15:03 UTC
http://www.mediafire.com/file/8fnlakn0fkq7xmn/goldfish.zip contains fishtest.blend, the .pmx that it exports, the .tif that it exports, a .png created from that .tif, and the original .3ds file that was imported into Blender, then joined with an existing .pmx model I had laying around (just to simplify getting all the MMD data that meshes need to export).

If you load the .pmx into EosCustom3D's 1.1 English translation (available at http://eoscustom3d.deviantart.com/art/English-Pmx-Editor-v1-1-542100208) you get an error: "Failed to initialize drawing."  You only get this error when textures\GOLDFISH.TIF exists and is accessible.  Opening the texture in an image editing program, then exporting it, and using that texture, fixes the issue.

So, obvious workaround, but it looks like you might be exporting texture images in a less-than-ideal fashion.

**Comment by powroupi** [comment] 2016-10-01 06:05
Thank you for reporting this issue. :smile: 

As far as i known, tif format is not supported yet, you can only use one of the following formats: **bmp, tga, jpg, dds and png** for MMD model. But i'm not sure about the full list of supported image formats... :worried:

So, i guess the exporter should be no problem. :smile:

**Comment by nathanvasil** [comment] 2016-10-01 14:55
I'm not sure I understand.  Let me clarify some things.

There is no .tif file that exists prior to the MMD Tools export.  MMD Tools export generates this file from information it gets from Blender, that Blender gets from running its own .3ds import script.

I know that Blender is capable of exporting images to different formats.  Exporting texture images (on MMD Tools export) to any of these formats would prevent future users from troubleshooting the same issue.

Failing that, if MMD Tools is creating texture fields with invalid textures, that's worse than leaving them blank.  These textures will never show, and will lead to errors that will confuse future users of MMD Tools.  If exporting to a valid file format isn't worth the trouble, then the next best thing is to not write invalid files/strings to any of the texture image fields in a .pmx or .pmd model.  Same as you wouldn't fill any other field with garbage.

**Comment by powroupi** [comment] 2016-10-02 01:17
Hmm, _fishtest.pmx_ indeed use 3 textures:
- tex\mug.png
- sph\sph3.png
- textures\GOLDFISH.TIF

In _fishtest.blend_, the MMD texture property of the material _gf_body_ is assigned to a tif image _GOLDFISH.TIF_, that information will be exported to pmx file. You could change it to a valid image or empty, or i might update the exporter to filter out unsupported image formats (but i need the full list of supported image formats >_<). Currently we rely on users to do that job.

(sorry for my english, hopefully the issue is more clear now)

**Comment by nathanvasil** [comment] 2016-10-02 01:45
Mug.png and sph3.png are from the .pmx file that I imported on top of the 3ds import, in order to attach valid MMD info (which is the easiest way I've found to get this info into new meshes).  They're not important.  After I do this, I just reimport and delete the mug material.

Goldfish.tif doesn't come from any .pmx.  It's the way that either Blender or MMD Tools handles the imported .3ds file, which has a texture image built in.

I've already taken care of the image/model.  I'm not concerned about a fix for this instance.  (I actually wasn't expecting to get texture info out anyways.)  And it's not a big deal to me, because it's easy to deal with once one understands what's happening.  It's only a concern for future users of MMD Tools, who will velieve, upon trying to get a 3ds mesh (maybe other meshes as well-- how does MMD Tools handle .blend files with built in textures?), that they have a broken model, and might give up rather than figure out what happened.

I believe your earlier list of supported image formats is complete.  I've never seen any model using any other formats.  (And many of those formats are poor choices in my opinion-- I don't see a reason to use anything except .png or .dds).  But of course, it's impossible to know if support was coded for something weird that nobody will ever bother trying.

**Comment by powroupi** [comment] 2016-10-02 07:37
Okay, so i think it might be the issue of documents, future users may feel frustrated about using my branch because of the lack of documents. Sorry, i'm not good at writing documents. :disappointed: 
(It would be great if people come to help writing documents)

But once you know how to use it, you'll know it is pretty simple to use, i think. :smile:

**Comment by nathanvasil** [comment] 2016-10-02 17:17
A list of known issues with workarounds could go a long ways, for sure.

I'd be happy to write some English documentation if you want, but there's a lot that I don't know about MMD Tools or Blender.

If you want help with this, it would require me asking you lots of dumb questions.  So many dumb questions that by the end of it, you would have been the one writing the documentation, with me just editing it.  But I would be more than happy to do so, if only for a chance to learn MMD Tools inside and out.

**Comment by powroupi** [comment] 2016-10-03 01:59
Okay, not bad i think. :smile:
I'll try my best to answer your questions, and you might edit those informations to proper documentation. Maybe we just need a rough documentation and a list of known issues with workarounds for beginners. :smile:

**Comment by nathanvasil** [comment] 2016-10-03 05:28
Well, if you don't mind, if I'm going to write docs, I'd rather do it well than just throw something together.  I made a new issue where I can ask questions related to it (including potential actual issues revealed by experimentation I need to do to write reasonable docs).

I'm going to leave this issue open, because I feel like this texture issue is something you might want to think about more, but of course, you're free to close it if you'd like.

**Comment by stefnotch** [comment] 2016-10-03 15:51
@nathanvasil Are you going to use github's Wiki feature? https://github.com/powroupi/blender_mmd_tools/wiki

**Comment by nathanvasil** [comment] 2016-10-03 20:37
I will now that you mention it, thanks!  WIP draft is at https://github.com/powroupi/blender_mmd_tools/wiki/Documentation-Draft

**Comment by powroupi** [comment] 2016-10-04 01:17
Looks great, appreciate your help and great work. :+1:

**Closed as completed** 2019-08-03 07:18 UTC
