### ISSUE TITLE
Keep getting this error when I try to install addon

### ISSUE THREAD

**Issue by faran99** [powroupi/blender_mmd_tools#314] opened 2020-10-28 03:50 UTC
![2020-10-27 (2)_LI](https://user-images.githubusercontent.com/73571295/97388688-fba1e780-18ae-11eb-9d12-049706f362e4.jpg)

It won't even let me load the addon to report a bug

Edit: Saw someone was having a similar problem so I followed the advice there and loaded the factory preferences then tried to reinstall the addon, but it still gave me the same error

**Comment by powroupi** [comment] 2021-05-21 01:45
Duplicate of #292

**Closed as completed by powroupi** 2021-05-21 01:45 UTC
Labels: Installation
