### ISSUE TITLE
Error during export to pmx

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#190] opened 2018-12-22 11:07 UTC
Someone got the following error when trying to export something to pmx: https://cdn.discordapp.com/attachments/387450722410561547/525976760601411584/unknown.png
Can you fix this or is this an user issue?

**Comment by powroupi** [comment] 2018-12-23 01:15
Thank you for reporting this issue, I'll check it. :smile:

I guess it is a bug of exporting a model with textures from different drives. Did he enable "Copy textures" when exporting the model?

**Comment by nathanvasil** [comment] 2018-12-23 01:27
I'm not up to date with the current version, but in case it helps, I get pack failures on save with models imported from my D:, and MMDT Convert To Cycles crashes Blender when using models I've imported from my D:.  On Win10.  Seems like it might be related, so thought I would share-- I've never really bothered making sure it had anything to do with MMD Tools, never bothered fully investigating.

**Comment by powroupi** [comment] 2018-12-23 03:14
Okay, the issue should be fixed now, you might try latest `mmd_tools`. Thank you. :smile:

>I get pack failures on save with models imported from my D:

@nathanvasil, try latest `mmd_tools` again, I think it should be fixed now. Thank you. :)

>Convert To Cycles crashes Blender when using models I've imported from my D:.

Will Blender never crash when using models imported from other drives (like C:)? Convert To Cycles crashes Blender sometimes, but I think it might probably be graphics driver issue. :thinking:

**Comment by nathanvasil** [comment] 2018-12-23 03:24
> Will Blender never crash when using models imported from other drives (like C:)? Convert To Cycles crashes Blender sometimes, but I think it might probably be graphics driver issue.

Nope, reliable with stuff imported from C:.  (That's what I do, just copy something to C: if I wanted to use Convert to Cycles, or reimported textures manually into materials.)

Untested on E: etc.

You want me to do some more testing?  Easy enough workaround that I never bothered.

**Comment by powroupi** [comment] 2018-12-23 07:18
>I get pack failures on save with models imported from my D:

Is the issue fixed when using latest `mmd_tools`? Is there any error message (or debug log) if the issue still exists?

>Nope, reliable with stuff imported from C:.

It's a little bit weird if `mmd_tools` can only use the stuff imported from C:. And I can't fix it if I can't reproduce the error. :cry:

>You want me to do some more testing?

It might help if there are some error messages from `C:\Users\XXXX\AppData\Local\Temp\blender.crash.txt` or Console Window when Blender crashes.

**Comment by nathanvasil** [comment] 2018-12-23 15:48
Errors on save/pack appear resolved with latest download.

Convert-to-cycles crashes are intermittent and it turns out they don't appear to have anything to do with D: vs C:.  That was just the first thing I tried, and then it didn't happen so I assumed that was the fix.  They happen about a third of the time in my recent testing, just appears random.

I don't see a log created from the crash in local/temp.  I ran from cmd to keep console window open, then recreated the crash, got the following traceback:

Read prefs: C:\Users\Craigslist\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
mmd_tools registed 127 classes
Exception ignored in: <bound method ImagePreviewCollection.__del__ of <ImagePreviewCollection id=0x220758a61d8[0], {}>>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\utils\previews.py", line 81, in __del__
    (self.__class__.__name__, self._uuid, len(self)))
ResourceWarning: <ImagePreviewCollection id=0x220758a61d8[0]>: left open, remove with 'bpy.utils.previews.remove()'
Read blend: C:\Users\Craigslist\Desktop\untitled.blend
Error: EXCEPTION_ACCESS_VIOLATION

**Comment by Darkblader24** [comment] 2018-12-23 16:39
The issue is fixed now, thanks!

**Comment by powroupi** [comment] 2018-12-24 00:54
@Darkblader24, you're welcome. I'll close this issue. :smile:

@nathanvasil, okay, the traceback is useful, and it seems to be a Blender's bug. You might try [@gitspyder's method](https://github.com/powroupi/blender_mmd_tools/issues/56#issuecomment-391103050) to see if it works for you or not. And we'll go to #56 which has similar issue of [Convert-to-cycles] to continue testing/debuging. Thank you. :smile:

**Closed as completed** 2018-12-24 00:54 UTC
