### ISSUE TITLE
bone pose morphs bone names disappear

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#171] opened 2018-09-13 09:45 UTC
Hello @powroupi ! I want to make a new bone pose morph. I want to add all of the names of the selected bones into this bone pose morph before I make the offsets for the bones. But in that case the names of the bones will all disappear when I click [Apply]. All bones which have no offset will disappear from the bone pose morph. Even if I use Blender's undo, I cannot recover the names of these bones in the bone pose morph. I have already wasted about an hour because of this issue.
Can you please fix this bug?

**Comment by Hogarth-MMD** [comment] 2018-09-13 10:12
Even if a bone originally had an offset in the bone pose morph, its name can still disappear from the bone pose morph. mmd_tools only accepts bones in the current pose which have offsets. One little mistake, the bones all disappear from the bone pose morph, and there is no undo for this.

**Comment by Hogarth-MMD** [comment] 2018-09-13 11:41
Why is not Blender's undo effective in this situation? How can a python command be added to ensure that Blender's undo is always effective?

EDIT: The undo seems to be having some effectiveness.

**Comment by Hogarth-MMD** [comment] 2018-09-13 12:20
For editing a bone morph, the labels and tool tips of buttons is confusing and unintuitive. 
There are 2 buttons which have the label Apply. This is confusing if I or someone else is asking for help with these 2 buttons. These 2 buttons should have different labels.

The button labels and the tool tips do not agree with each other. Edit is Apply and Apply is Store. Meanwhile the average user of MMD does not even understand the meaning of "Apply".

**Comment by Hogarth-MMD** [comment] 2018-09-14 00:12
When editing morphs, mmd_tools does not prevent duplicate listing of names. There can be duplicate listing of bone names in a bone morph, duplicate listing of material names in a material morph, and duplicate listing of morph names in a group morph.

**Comment by powroupi** [comment] 2018-09-14 01:10
>when I click [Apply]. All bones which have no offset will disappear from the bone pose morph.

Yeah, because those data are not functional, there is no reason to keep them. Normally, you only need to pose your model and then [Apply] current pose to active bone morph when adding a bone pose morph. And from my test, undo is functional if [Global Undo](https://docs.blender.org/manual/ja/dev/preferences/editing.html#undo) is enabled.

>When editing morphs, mmd_tools does not prevent duplicate listing of names.

Yeah, MMD does not prevent this and it may be functional. I've tested material/group morphs.

**Comment by Hogarth-MMD** [comment] 2018-09-14 09:23
Suggested changes to the button labels and tooltips for bone morph editing:

[Preview Morph] "Armature is posed to preview this bone morph."
[Replace Morph] "Bone morph is replaced and overwritten by the armature's current pose."
[Clear] "Reset armature's selected bones to their default location, rotation and scale."

[Select] "Select this offset's bone in the armature."
[Preview Offset] "Bone is posed to preview this bone offset"
[Replace Offset] "Bone offset is replaced and overwritten by this bone's current pose"

**Comment by Hogarth-MMD** [comment] 2018-09-14 09:29
> Yeah, because those data are not functional, there is no reason to keep them.

This is an incorrect idea. This idea wrongly assumes that a bone morph edit will happen completely in only one session and one stage. But someone may want to make a bone morph edit in several stages/sessions.

**Comment by Hogarth-MMD** [comment] 2018-09-14 09:32
> Yeah, MMD does not prevent this and it may be functional. I've tested material/group morphs.

So what happens if 2 duplicate offsets contradict each other? How is this conflict resolved? Almost no users of MMD or mmd_tools know the answer to this question, so it is a bug of MMD and mmd_tools.

**Comment by powroupi** [comment] 2018-09-15 01:21
>Suggested changes to the button labels and tooltips for bone morph editing:

I can update tooltips, but I like current labels (View, Apply, Clear, Edit) used in different morph types. :blush: 

>This idea wrongly assumes that a bone morph edit will happen completely in only one session and one stage.

If you want to make a bone morph edit in several stages/sessions,  click [View], pose other bones, and then [Apply]. I think this way is more efficient. :)

>So what happens if 2 duplicate offsets contradict each other?

You can test it by yourself. Currently [Bind] function of mmd_tools does not work properly if there are duplicate group morph offsets or duplicate morph names, and material morph is not supported yet. In MMD, duplicate morph names may cause issues when making/loading VMD. Duplicate offsets will work fine, for example, you get bone offset 2 unit in X-axis if you add bone offset 1 unit in X-axis twice.

**Comment by Hogarth-MMD** [comment] 2018-09-15 16:23
@powroupi wrote:
"I can update tooltips, but I like current labels (View, Apply, Clear, Edit)"

For editing bone morphs, there are 2 buttons with the label "Apply".  This is a problem for me to make a tutorial. What should I call these buttons? Apply upper and Apply lower? Apply 1 and Apply 2? I really think that these duplicate labels are an mmd_tools bug.

**Comment by powroupi** [comment] 2018-09-16 01:10
How about just changing [Apply] bone offset to [Update] (or [Replace]) bone offset, so we have `View/Apply/Clear` and `Select/Edit/Update(or Replace)` without conflicts?

**Comment by Hogarth-MMD** [comment] 2018-09-16 02:26
I don't really see why the lower [Apply] button is needed. If I am understanding correctly, it seems to me that applying each and every bone offset one at a time just wastes time. Maybe there should be one [Apply] button which applies all bone offsets from the Armature pose at the same time., with an option to preserve all bone names in the morph, even if they have no offset.

The UV morph editing and bone morph editing both have a danger that the user can erase data, and the user needs to be warned about this possibility. I am not sure if this is needed, or if this is the best idea, but maybe a popup dialog warning the user(?).

**Comment by powroupi** [comment] 2018-09-16 02:59
I think we should add warning to tooltips, popup dialog isn't a good idea. You could apply your edit to a new (temporary) morph to prevent overwriting original morph, once you satisfied with your edit, you can remove original morph then. :)

Generally, you only need the function of [Apply] bone morph, [Apply] bone offset is a legacy function.

**Comment by Hogarth-MMD** [comment] 2018-09-16 16:11
> How about just changing [Apply] bone offset to [Update] (or [Replace]) bone offset, so we have `View/Apply/Clear` and `Select/Edit/Update(or Replace)` without conflicts?

That would be fine, or maybe just [Apply bone]

**Comment by Hogarth-MMD** [comment] 2018-09-16 16:15
"You could apply your edit to a new (temporary) morph to prevent overwriting original morph, once you satisfied with your edit, you can remove original morph then. :)"

This seems to be an excellent idea. To make this user-friendly, we need to have a new "Copy Morph" command added to the Morph Tools Panel. I request and recommend to @powroupi  the addition of a "Copy Morph" command to the Morph Tools Panel. :smile:

**Comment by Hogarth-MMD** [comment] 2018-09-16 16:20
So, now I understand that only the top 3 buttons are needed to edit a bone pose morph. The other buttons are not needed. They were created as part of the development of the edit bone morph feature, but now they are not needed when editing a bone pose morph.

**Comment by powroupi** [comment] 2018-09-18 01:08
Okay, I've added "Copy Morph" command to the Morph Tools Panel (1c8c51e), and changed label [Apply] bone offset to [Update] bone offset. Duplicate morph names will be corrected on import. :smile: 

Note: Stored UV vertex groups and shape keys will not be removed when removing the morph item, you may click "X" button to clear morph offset data first, or remove them manually.

**Comment by Hogarth-MMD** [comment] 2018-09-18 21:14
Thanks @powroupi . :smile: You are an amazingly talented programmer of mmd_tools.

**Closed as completed** 2018-09-20 20:52 UTC
