### ISSUE TITLE
This addon doesn't work on Blender 2.93 Beta

### ISSUE THREAD

**Issue by MicheleGiunto** [powroupi/blender_mmd_tools#339] opened 2021-04-22 18:16 UTC
**When I try to import a PMX file**

Traceback (most recent call last):
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\operators\fileio.py", line 159, in execute
    self.__translator = DictionaryEnum.get_translator(self.dictionary)
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\translations.py", line 323, in get_translator
    return getTranslator(dictionary)
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\translations.py", line 171, in getTranslator
    elif csvfile in bpy.data.texts:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

Python: Traceback (most recent call last):
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\panels\prop_material.py", line 38, in draw
    if not mmd_material.is_id_unique():
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\properties\material.py", line 261, in is_id_unique
    return self.material_id < 0 or not next((m for m in bpy.data.materials if m.mmd_material != self and m.mmd_material.material_id == self.material_id), None)
TypeError: '<' not supported between instances of '_PropertyDeferred' and 'int'

location: <unknown location>:-1

Python: Traceback (most recent call last):
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\mmd_tools\panels\prop_material.py", line 129, in draw
    r.active = mmd_material.is_shared_toon_texture
TypeError: bpy_struct: item.attr = val: UILayout.active expected True/False or 0/1, not _PropertyDeferred

location: <unknown location>:-1

Python: Traceback (most recent call last):
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\poliigon-material-converter\poliigon_ui.py", line 90, in draw
    addon_updater_ops.check_for_update_background()
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\poliigon-material-converter\addon_updater_ops.py", line 727, in check_for_update_background
    updater.set_check_interval(enable=settings.auto_check_update,
  File "D:\APPS PORTATILI\Blender\B2.93\2.93\scripts\addons\poliigon-material-converter\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1

**Works on 2.92 like a charm. Only 2.93 gives me this error.
Didn't test on 3.0 alpha but I think it's the same.
Same problem with CATS.**

**Comment by nagadomi** [comment] 2021-04-23 12:22
I've send Pull Request #338 to fix this error, but may not be merged until the official release of Blender 2.93.
If you want it to work as soon as possible, change the following few lines to make it work.
https://github.com/powroupi/blender_mmd_tools/pull/338/files

Note that this error is caused by a change described in the Release Notes 2.93 as ["While this is not considered part of the stable API"](https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API), which may change before the official release.

**Closed as completed** 2021-05-21 00:57 UTC
